



package project;


import java.sql.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;





public class SymptomAnalyzer extends javax.swing.JFrame {
Connection con;

 SignIn acc= new SignIn();
    /**
     * Creates new form SymptomAnalyzer
     */
    public SymptomAnalyzer() {
        initComponents();
     
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/VRC", "root", "Sh$123456");
        } catch (SQLException ex) {
            Logger.getLogger(SymptomAnalyzer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SymptomAnalyzer.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        panel1 = new java.awt.Panel();
        profileIcon = new javax.swing.JLabel();
        ProfilePic = new javax.swing.JLabel();
        home3 = new javax.swing.JButton();
        appointment = new javax.swing.JButton();
        booking = new javax.swing.JButton();
        contacts = new javax.swing.JButton();
        FAQ = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ageTF = new java.awt.TextField();
        label2 = new java.awt.Label();
        RadioButtonYES = new javax.swing.JRadioButton();
        RadioButtonNO = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        label3 = new java.awt.Label();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBoxNONE = new javax.swing.JCheckBox();
        javax.swing.JButton SubmitButton = new javax.swing.JButton();
        VRClogo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(193, 244, 197));
        panel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel1.setName(""); // NOI18N
        panel1.setPreferredSize(new java.awt.Dimension(133, 364));

        profileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/profile.png"))); // NOI18N

        ProfilePic.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        home3.setBackground(new java.awt.Color(244, 245, 239));
        home3.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 12)); // NOI18N
        home3.setText("Home");
        home3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home3ActionPerformed(evt);
            }
        });

        appointment.setBackground(new java.awt.Color(244, 245, 239));
        appointment.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 10)); // NOI18N
        appointment.setForeground(new java.awt.Color(51, 51, 51));
        appointment.setText("<html>\nMy \nAppointments");
        appointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointmentActionPerformed(evt);
            }
        });

        booking.setBackground(new java.awt.Color(244, 245, 239));
        booking.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 10)); // NOI18N
        booking.setForeground(new java.awt.Color(51, 51, 51));
        booking.setText("<html>\nBook An  \nAppointment");
        booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingActionPerformed(evt);
            }
        });

        contacts.setBackground(new java.awt.Color(244, 245, 239));
        contacts.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 12)); // NOI18N
        contacts.setForeground(new java.awt.Color(51, 51, 51));
        contacts.setText("<html>\nHealthcare\nContacts");
        contacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactsActionPerformed(evt);
            }
        });

        FAQ.setBackground(new java.awt.Color(244, 245, 239));
        FAQ.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 12)); // NOI18N
        FAQ.setForeground(new java.awt.Color(51, 51, 51));
        FAQ.setText("FAQ's");
        FAQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FAQActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(244, 245, 239));
        logout.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 12)); // NOI18N
        logout.setForeground(new java.awt.Color(51, 51, 51));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(home3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appointment, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(booking, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contacts, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FAQ, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profileIcon)
                    .addComponent(ProfilePic))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profileIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProfilePic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(home3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(appointment, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(booking, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contacts, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FAQ, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel1.setText("Symptom Analyzer");

        ageTF.setBackground(new java.awt.Color(255, 255, 255));
        ageTF.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        ageTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ageTFMouseEntered(evt);
            }
        });
        ageTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTFActionPerformed(evt);
            }
        });
        ageTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ageTFKeyPressed(evt);
            }
        });

        label2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        label2.setText("Age :");

        buttonGroup1.add(RadioButtonYES);
        RadioButtonYES.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        RadioButtonYES.setText("Yes");
        RadioButtonYES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonYESActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioButtonNO);
        RadioButtonNO.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        RadioButtonNO.setText("No");
        RadioButtonNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonNOActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel2.setText("Any recent contact with a  Covid-19 patient in the last 14 days?");
        jLabel2.setAlignmentY(3.0F);

        label3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        label3.setText("Do you have one or more of the following symptoms?");

        jCheckBox1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jCheckBox1.setText("Fever");
        jCheckBox1.setMultiClickThreshhold(5L);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jCheckBox2.setText("Dry throat");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jCheckBox3.setText("Shortness of breath");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jCheckBox4.setText("Headaches");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jCheckBox5.setText("Running nose");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jCheckBoxNONE.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jCheckBoxNONE.setText("None");
        jCheckBoxNONE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxNONEActionPerformed(evt);
            }
        });

        SubmitButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        SubmitButton.setText("SUBMIT");
        SubmitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitButtonMouseClicked(evt);
            }
        });
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        VRClogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/vrc.png"))); // NOI18N

        jButton1.setText("get age");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(RadioButtonYES)
                                        .addGap(18, 18, 18)
                                        .addComponent(RadioButtonNO))
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(271, 271, 271)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                        .addComponent(VRClogo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jCheckBox4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jCheckBox3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxNONE, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(228, 228, 228)
                                .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(VRClogo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadioButtonYES)
                            .addComponent(RadioButtonNO))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxNONE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ageTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTFActionPerformed
// int age;
//  
//
//age = Integer.parseInt(ageTF.getText());
//if(age >=60) 
//    JOptionPane.showMessageDialog(this, "Vaccinating at your age is very risky.");
//else if (age<12)
//        JOptionPane.showMessageDialog(this, "You are too young to vaccinate.");


    }//GEN-LAST:event_ageTFActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        String age;
age = ageTF.getText();

        if (RadioButtonYES.isSelected())
           if (jCheckBox1.isSelected() || jCheckBox2.isSelected() || jCheckBox3.isSelected() || jCheckBox4.isSelected() || jCheckBox5.isSelected())
               JOptionPane.showMessageDialog(null, "You are denied an appointment. We urge you to get a Covid-19 test and quarantine.");
        
        //JframePage is the name of the next page(Jframe), Jf2 is the variable.
                Appointment Jf2 = new Appointment();
       if (RadioButtonNO.isSelected()){
           if (jCheckBoxNONE.isSelected()){
               if (Double.parseDouble(age) >=12 && Double.parseDouble(age) <60)
                   Jf2.show(); //to show the next page
                   dispose();} 
       
       } // to close the previous page after opening the next.
       if (RadioButtonNO.isSelected()){
           if(jCheckBox1.isSelected() || jCheckBox2.isSelected() || jCheckBox3.isSelected() || jCheckBox4.isSelected() || jCheckBox5.isSelected())
           JOptionPane.showMessageDialog(this, "It is best for you to wait 5 days before booking a vaccine, to check for any symptoms."); 
           this.setVisible(false);
           Jf2.setVisible(true);
       }
     
           
       
       if (RadioButtonNO.isSelected())
           if (jCheckBoxNONE.isSelected())
               if(Double.parseDouble(age)>=60)
              JOptionPane.showMessageDialog(this, "Your age poses a high risk."); 
       
       if (RadioButtonNO.isSelected())
           if (jCheckBoxNONE.isSelected())
               if(Double.parseDouble(age)<12)
              JOptionPane.showMessageDialog(this, "You are too young to vaccinate."); 
       
            
       
       
       if (RadioButtonYES.isSelected())
           if (jCheckBoxNONE.isSelected())
              JOptionPane.showMessageDialog(this, "It is best for you to wait 5 days before booking a vaccine, to check for any symptoms."); 
      
       
        
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void ageTFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ageTFMouseEntered

    }//GEN-LAST:event_ageTFMouseEntered

    private void RadioButtonYESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonYESActionPerformed
        // TODO add your handling code here:
        if (RadioButtonYES.isSelected())
            RadioButtonNO.setSelected(false);
    }//GEN-LAST:event_RadioButtonYESActionPerformed

    private void SubmitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButtonMouseClicked
    
    }//GEN-LAST:event_SubmitButtonMouseClicked

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
         if (jCheckBox3.isSelected())
            jCheckBoxNONE.setSelected(false);
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void RadioButtonNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonNOActionPerformed
        // TODO add your handling code here:
         if (RadioButtonNO.isSelected())
            RadioButtonYES.setSelected(false);
    }//GEN-LAST:event_RadioButtonNOActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
         if (jCheckBox2.isSelected())
            jCheckBoxNONE.setSelected(false);
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBoxNONEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxNONEActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxNONE.isSelected()) {
            jCheckBox1.setSelected(false);
            jCheckBox2.setSelected(false);
            jCheckBox3.setSelected(false);
            jCheckBox4.setSelected(false);
            jCheckBox5.setSelected(false);
            
    }
        
    }//GEN-LAST:event_jCheckBoxNONEActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected())
            jCheckBoxNONE.setSelected(false);
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
         if (jCheckBox4.isSelected())
            jCheckBoxNONE.setSelected(false);
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
         if (jCheckBox5.isSelected())
            jCheckBoxNONE.setSelected(false);
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void ageTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageTFKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTFKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      String age;
        Statement st;
 String ageQuery="SELECT DATE_FORMAT(FROM_DAYS(DATEDIFF(now(),User.BDate)), '%Y')+0 AS Age FROM User WHERE SSN = "+SignIn.acc.getUserName();
  ResultSet rs;
    try {
        st=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
        rs=st.executeQuery(ageQuery);
        
        if(rs.next()){
            ageTF.setText(rs.getString("Age"));
            age=ageTF.getText();
            if(Double.parseDouble(age) >=60) 
    JOptionPane.showMessageDialog(this, "Vaccinating at your age is very risky.");
else if (Double.parseDouble(age)<12)
        JOptionPane.showMessageDialog(this, "You are too young to vaccinate.");
        }
        
    } catch (SQLException ex) {
        Logger.getLogger(SymptomAnalyzer.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void home3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home3ActionPerformed
        this.setVisible(false);
        HomePage h=new HomePage();
        h.setVisible(true);
    }//GEN-LAST:event_home3ActionPerformed

    private void appointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentActionPerformed
        this.setVisible(false);
        AppFrame a= new AppFrame();
        a.setVisible(true);
    }//GEN-LAST:event_appointmentActionPerformed

    private void bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingActionPerformed
        if(acc.validUser()){
            this.setVisible(false);
            SymptomAnalyzer a=new SymptomAnalyzer();
            a.setVisible(true);
        }
        else{
            this.setVisible(false);
            Vaccine a=new Vaccine();
            a.setVisible(true);}
    }//GEN-LAST:event_bookingActionPerformed

    private void contactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactsActionPerformed
        this.setVisible(false);
        HCP c=new HCP();
        c.setVisible(true);
    }//GEN-LAST:event_contactsActionPerformed

    private void FAQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FAQActionPerformed
        this.setVisible(false);
        FAQFrame faq=new FAQFrame();
        faq.setVisible(true);
    }//GEN-LAST:event_FAQActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        this.setVisible(false);
        SignIn l=new SignIn();
        l.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

   
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FAQ;
    private javax.swing.JLabel ProfilePic;
    private javax.swing.JRadioButton RadioButtonNO;
    private javax.swing.JRadioButton RadioButtonYES;
    private javax.swing.JLabel VRClogo;
    private java.awt.TextField ageTF;
    private javax.swing.JButton appointment;
    private javax.swing.JButton booking;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton contacts;
    private javax.swing.JButton home;
    private javax.swing.JButton home1;
    private javax.swing.JButton home2;
    private javax.swing.JButton home3;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBoxNONE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JButton logout;
    private java.awt.Panel panel1;
    private javax.swing.JLabel profileIcon;
    // End of variables declaration//GEN-END:variables
}
